Algoritmo "EXERCICIO_ENQUANTO_3"

Var

   x : inteiro

Inicio

   escreva("Digite sua senha: ")
   leia(x)
   
   se x = 2002 entao
      escreva("Acesso permitido!")
      senao
      enquanto x <> 2002 faca
         escreva("Senha invalida! Tente novamente: ")
         leia(x)
         se x = 2002 entao
            escreva("Acesso permitido!")
         fimse
      fimenquanto
   fimse
   

   
      
      


   
   

Fimalgoritmo