Algoritmo "EXERCICIO_PARA_6"

Var

   n, i : inteiro
   x, y, z, media : real

Inicio

   escreva("Quantos casos voce vai digitar? ")
   leia(n)
   
   para i de 1 ate n faca
   
   escreval("Digite tres numeros:")

   leia(x)
   leia(y)
   leia(z)
   
   media <- 0
   media <-  ((x * 2) + (y * 3) + (z * 5)) / 10
   
   escreval("MEDIA = ", media:3:1)
   fimpara
      
      

      



Fimalgoritmo